// Test CA certificate, generated by host/gen_test_certs.sh - do not edit
static const char test_ca_cert[] =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBjTCCATOgAwIBAgIUJyqC7mxyiPFiHaBBAux5H3U1rTUwCgYIKoZIzj0EAwIw\n"
    "HDEaMBgGA1UEAwwRcGljby1odHRwLXRlc3QgQ0EwHhcNMjYwODI0MDc0OTE0WhcN\n"
    "MzYwODIxMDc0OTE0WjAcMRowGAYDVQQDDBFwaWNvLWh0dHAtdGVzdCBDQTBZMBMG\n"
    "ByqGSM49AgEGCCqGSM49AwEHA0IABLBRgDepu8s0veZfEahXYVE7wdQnYKj9dL9h\n"
    "B1Azd2gyx7l/VD26mWwYRFQkE2T5NA0RV+xuzpoy1qeKteIErOijUzBRMB0GA1Ud\n"
    "DgQWBBSZGGQtcNXPkj7hH7sxgzWSAaLSYTAfBgNVHSMEGDAWgBSZGGQtcNXPkj7h\n"
    "H7sxgzWSAaLSYTAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gAMEUCIGrk\n"
    "29ui+d0tMZpKhIzNgAL99wH5TcKkmmi5LrU2AneIAiEAmpjdRxOkspdle5ohF/0V\n"
    "dGKjlT/IlqKxhUpsRDvnkDY=\n"
    "-----END CERTIFICATE-----\n"
    ;
