#!/bin/bash
# Generate the TLS test credentials for pico_rpi_connect_http_test:
#   certs/ca.crt, ca.key            test CA; the CA cert is also written to
#                                   ../test_ca_cert.h to build into the firmware
#   certs/server.crt, server.key    server certificate signed by the test CA
#   certs/untrusted.crt, .key       self-signed certificate NOT signed by the
#                                   CA, served on the untrusted port
#
# Test-only credentials: the outputs are committed so firmware and harness
# stay in sync. Re-run this script to rotate them (rebuild afterwards).
#
# The certificates name the AP address (10.42.0.1): the client sets it as the
# TLS hostname, and mbedtls string-matches it against the SAN/CN.

set -e
cd "$(dirname "$0")"
mkdir -p certs

HOST=10.42.0.1
DAYS=3650

openssl ecparam -name prime256v1 -genkey -noout -out certs/ca.key
openssl req -new -x509 -key certs/ca.key -out certs/ca.crt -days $DAYS \
    -subj "/CN=pico-http-test CA"

openssl ecparam -name prime256v1 -genkey -noout -out certs/server.key
openssl req -new -key certs/server.key -subj "/CN=$HOST" |
    openssl x509 -req -CA certs/ca.crt -CAkey certs/ca.key -CAcreateserial \
        -out certs/server.crt -days $DAYS \
        -extfile <(echo "subjectAltName=DNS:$HOST,IP:$HOST")

openssl ecparam -name prime256v1 -genkey -noout -out certs/untrusted.key
openssl req -new -x509 -key certs/untrusted.key -out certs/untrusted.crt \
    -days $DAYS -subj "/CN=$HOST" \
    -addext "subjectAltName=DNS:$HOST,IP:$HOST"

{
    echo "// Test CA certificate, generated by host/gen_test_certs.sh - do not edit"
    echo "static const char test_ca_cert[] ="
    sed 's/.*/    "&\\n"/' certs/ca.crt
    echo "    ;"
} > ../test_ca_cert.h

echo "Wrote certs/ and ../test_ca_cert.h"
